#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File   : cleanup.py
# License: GNU v3.0
# Author : Andrei Leonard Nicusan <a.l.nicusan@bham.ac.uk>
# Date   : 02.03.2022


import os
import shutil


def cleanup(
    files = [
        "med_single_script1.py",
        "med_single_script2.py",
        "med_multi_script1.py",
        "med_multi_script2.py",
    ],
    directories = [
        "__pycache__",
        "med_seed123",
        "med_seed124",
        "med_single_local",
        "med_single_parallel",
        "med_multi_local",
        "med_multi_parallel",
    ],
):
    '''Remove files and directories generated by running tests.
    '''

    for f in files:
        if os.path.isfile(f):
            os.remove(f)

    for d in directories:
        if os.path.isdir(d):
            shutil.rmtree(d)


if __name__ == "__main__":
    cleanup()
